version: '3.8'

services:
  # Firebase Emulator Suite
  firebase-emulator:
    image: node:24-alpine
    container_name: stall-bokning-firebase-emulator
    working_dir: /app
    command: >
      sh -c "apk add --no-cache openjdk21-jre-headless &&
             npm install -g firebase-tools &&
             firebase emulators:start --only firestore,auth --project=stall-bokning-dev"
    environment:
      - FIRESTORE_EMULATOR_HOST=0.0.0.0:5081
      - FIREBASE_AUTH_EMULATOR_HOST=0.0.0.0:5099
    ports:
      - "5444:4000"   # Emulator UI
      - "5081:5081"   # Firestore
      - "5099:5099"   # Auth
    volumes:
      - firebase-data:/root/.config
      - ../../firebase.json:/app/firebase.json:ro
    networks:
      - stall-bokning-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # API Gateway (Fastify)
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stall-bokning-api
    ports:
      - "5003:8080"
    environment:
      PORT: 8080
      HOST: 0.0.0.0
      NODE_ENV: development
      FIRESTORE_EMULATOR_HOST: firebase-emulator:5081
      FIREBASE_AUTH_EMULATOR_HOST: firebase-emulator:5099
      CORS_ORIGIN: http://localhost:5173
      RATE_LIMIT_MAX: 1000
      RATE_LIMIT_WINDOW_MS: 60000
      GOOGLE_CLOUD_PROJECT: stall-bokning-dev
    depends_on:
      firebase-emulator:
        condition: service_healthy
    networks:
      - stall-bokning-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  stall-bokning-network:
    driver: bridge

volumes:
  firebase-data:
    driver: local
