export const DEFAULT_QUICK_ACTIONS = [
  {
    id: "today-schedule",
    label: "Today's Schedule",
    labelSv: "Dagens schema",
    icon: "calendar",
    query: "What's on the schedule for today?",
    category: "schedule",
  },
  {
    id: "pending-tasks",
    label: "Pending Tasks",
    labelSv: "Väntande uppgifter",
    icon: "check-square",
    query: "Show me pending tasks",
    category: "tasks",
  },
  {
    id: "low-inventory",
    label: "Low Stock Items",
    labelSv: "Lågt lager",
    icon: "package",
    query: "What items are running low in inventory?",
    category: "inventory",
  },
  {
    id: "horse-status",
    label: "Horse Status",
    labelSv: "Häststatus",
    icon: "activity",
    query: "Give me an overview of all horses",
    category: "horses",
  },
  {
    id: "upcoming-vet",
    label: "Upcoming Vet Visits",
    labelSv: "Kommande veterinärbesök",
    icon: "stethoscope",
    query: "When are the next vet appointments?",
    category: "schedule",
  },
  {
    id: "weekly-summary",
    label: "Weekly Summary",
    labelSv: "Veckosammanfattning",
    icon: "bar-chart",
    query: "Give me a summary of this week",
    category: "analytics",
  },
  {
    id: "feeding-schedule",
    label: "Feeding Schedule",
    labelSv: "Utfodringsschema",
    icon: "utensils",
    query: "Show me today's feeding schedule",
    category: "schedule",
  },
  {
    id: "overdue-invoices",
    label: "Overdue Invoices",
    labelSv: "Förfallna fakturor",
    icon: "file-text",
    query: "Are there any overdue invoices?",
    category: "analytics",
  },
];
