// ============================================================
// Standard Templates (Pre-configured Swedish patterns)
// ============================================================
/**
 * Standard Swedish routine template definitions
 * Used for seeding new organizations
 */
export const STANDARD_ROUTINE_TEMPLATES = [
  {
    name: "Morgonpass",
    description: "Standard morgonrutin för stallet",
    type: "morning",
    icon: "sun",
    color: "#FFA500",
    defaultStartTime: "06:30",
    estimatedDuration: 90,
    requiresNotesRead: true,
    allowSkipSteps: true,
    pointsValue: 3,
    isActive: true,
    steps: [
      {
        id: "step-1",
        order: 1,
        name: "Läs dagens notiser",
        description: "Kontrollera dagens anteckningar och varningar",
        category: "preparation",
        icon: "clipboard",
        horseContext: "none",
        requiresConfirmation: true,
        allowPartialCompletion: false,
        estimatedMinutes: 5,
      },
      {
        id: "step-2",
        order: 2,
        name: "Morgonfodring",
        description: "Ge morgonfoder och tillskott till alla hästar",
        category: "feeding",
        icon: "utensils",
        horseContext: "all",
        showFeeding: true,
        showMedication: true,
        showSpecialInstructions: true,
        requiresConfirmation: true,
        allowPartialCompletion: true,
        allowPhotoEvidence: true,
        estimatedMinutes: 30,
      },
      {
        id: "step-3",
        order: 3,
        name: "Täckehantering",
        description: "Ta av/på täcken efter dagens väder",
        category: "blanket",
        icon: "coat",
        horseContext: "all",
        showBlanketStatus: true,
        requiresConfirmation: true,
        allowPartialCompletion: true,
        estimatedMinutes: 20,
      },
      {
        id: "step-4",
        order: 4,
        name: "Utsläpp",
        description: "Släpp ut hästarna i sina hagar",
        category: "turnout",
        icon: "gate",
        horseContext: "all",
        showSpecialInstructions: true,
        requiresConfirmation: true,
        allowPartialCompletion: true,
        estimatedMinutes: 25,
      },
      {
        id: "step-5",
        order: 5,
        name: "Vattencheck",
        description: "Kontrollera vatten i boxar och hinkar",
        category: "water",
        icon: "droplet",
        horseContext: "none",
        requiresConfirmation: true,
        allowPartialCompletion: false,
        estimatedMinutes: 10,
      },
    ],
  },
  {
    name: "Dagpass",
    description: "Lunchrutin med mockning",
    type: "midday",
    icon: "clock",
    color: "#4CAF50",
    defaultStartTime: "11:00",
    estimatedDuration: 120,
    requiresNotesRead: true,
    allowSkipSteps: true,
    pointsValue: 4,
    isActive: true,
    steps: [
      {
        id: "step-1",
        order: 1,
        name: "Läs notiser",
        description: "Kontrollera eventuella uppdateringar",
        category: "preparation",
        icon: "clipboard",
        horseContext: "none",
        requiresConfirmation: true,
        allowPartialCompletion: false,
        estimatedMinutes: 5,
      },
      {
        id: "step-2",
        order: 2,
        name: "Mockning",
        description: "Mocka alla boxar",
        category: "mucking",
        icon: "broom",
        horseContext: "all",
        requiresConfirmation: true,
        allowPartialCompletion: true,
        allowPhotoEvidence: true,
        estimatedMinutes: 90,
      },
      {
        id: "step-3",
        order: 3,
        name: "Lunchfodring",
        description: "Ge lunchtillägg om tillämpligt",
        category: "feeding",
        icon: "utensils",
        horseContext: "all",
        showFeeding: true,
        showMedication: true,
        requiresConfirmation: true,
        allowPartialCompletion: true,
        estimatedMinutes: 15,
      },
      {
        id: "step-4",
        order: 4,
        name: "Vattencheck i hagar",
        description: "Kontrollera vatten i alla hagar",
        category: "water",
        icon: "droplet",
        horseContext: "none",
        requiresConfirmation: true,
        allowPartialCompletion: false,
        estimatedMinutes: 10,
      },
    ],
  },
  {
    name: "Kvällspass",
    description: "Standard kvällsrutin för stallet",
    type: "evening",
    icon: "moon",
    color: "#3F51B5",
    defaultStartTime: "16:30",
    estimatedDuration: 90,
    requiresNotesRead: true,
    allowSkipSteps: true,
    pointsValue: 3,
    isActive: true,
    steps: [
      {
        id: "step-1",
        order: 1,
        name: "Läs notiser",
        description: "Kontrollera eventuella uppdateringar",
        category: "preparation",
        icon: "clipboard",
        horseContext: "none",
        requiresConfirmation: true,
        allowPartialCompletion: false,
        estimatedMinutes: 5,
      },
      {
        id: "step-2",
        order: 2,
        name: "Insläpp",
        description: "Hämta in alla hästar från hagen",
        category: "bring_in",
        icon: "home",
        horseContext: "all",
        showSpecialInstructions: true,
        requiresConfirmation: true,
        allowPartialCompletion: true,
        estimatedMinutes: 25,
      },
      {
        id: "step-3",
        order: 3,
        name: "Kvällsfodring",
        description: "Ge kvällsfoder, hö och mediciner",
        category: "feeding",
        icon: "utensils",
        horseContext: "all",
        showFeeding: true,
        showMedication: true,
        showSpecialInstructions: true,
        requiresConfirmation: true,
        allowPartialCompletion: true,
        allowPhotoEvidence: true,
        estimatedMinutes: 35,
      },
      {
        id: "step-4",
        order: 4,
        name: "Täcke på",
        description: "Lägg på nattäcken på de hästar som behöver",
        category: "blanket",
        icon: "coat",
        horseContext: "all",
        showBlanketStatus: true,
        requiresConfirmation: true,
        allowPartialCompletion: true,
        estimatedMinutes: 15,
      },
      {
        id: "step-5",
        order: 5,
        name: "Säkerhetskontroll",
        description: "Kontrollera dörrar, vatten, belysning",
        category: "safety",
        icon: "shield",
        horseContext: "none",
        requiresConfirmation: true,
        allowPartialCompletion: false,
        estimatedMinutes: 10,
      },
    ],
  },
];
